# Generated by Django 6.0.3 on 2026-04-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='admission_documents/', verbose_name='Hujjat fayli'),
        ),
    ]
