# Generated by Django 6.0.3 on 2026-04-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcement_images/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rasm izohi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.announcement', verbose_name="E'lon")),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'db_table': 'announcement_images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['announcement', 'sort_order'], name='announcemen_announc_63369a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rasm izohi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari',
                'db_table': 'news_images',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['news', 'sort_order'], name='news_images_news_id_c5873c_idx')],
            },
        ),
    ]
