# Generated by Django 6.0.3 on 2026-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_announcementimage_newsimage'),
    ]

    operations = [
        # Yangi image field qo'shish
        migrations.AddField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(upload_to='announcement_images/', null=True, verbose_name='Rasm'),
        ),
        # Eski image_url ni o'chirish
        migrations.RemoveField(
            model_name='announcementimage',
            name='image_url',
        ),
        # Image field ni not null qilish
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(upload_to='announcement_images/', verbose_name='Rasm'),
        ),
    ]
